### ISSUE TITLE
blast2genomegff.py missing in repository

### ISSUE THREAD

**Issue by Eduardo-Alves** [wrf/genomeGTFtools#1]
Missing blast2genomegff.py but found it in youre bitbucket https://bitbucket.org/wrf/sequences/src
Also, are you ok with wrapping the repository into a usegalaxy.org tool?

**Comment by wrf** [comment]
Thanks for letting me know. Regarding galaxy, if you were on track to write a wrapper, please go ahead, as I may not get to this any time soon.

**Comment by Eduardo-Alves** [comment]
Thank you, will do.
I have a quick question. How would you approach converting a blastp result
on a protein prediction for a contig such as the transdecoder? I'm thinking
of passing the predicted mrna gff and multiply all protein query
coordinates by three but not sure if this would work.

Eduardo

**Comment by wrf** [comment]
If the first base of the transcript is the start of the CDS, then that would work, otherwise you have to offset the start of the protein within the transcript. I think I have implemented something similar in the pfam2gff.py script that makes use of the TransDecoder genome gff output, which includes both exon and CDS features.

**Comment by Eduardo-Alves** [comment]
Thank you, I will look into that as it should be similar to what I am
trying to do.

Eduardo
