### ISSUE TITLE
microsynteny.py: GFF input for bacterial genomes

### ISSUE THREAD

**Issue by sarah872** [wrf/genomeGTFtools#11]
Hi,
I have a problem running the `microsynteny.py`. I have rather verbose gff files for bacterial genomes, so not the intron-exon examples you have. I suppose there is something wrong with parsing the gffs?

I attached both gff-files and the blast output.
This is how I am running the script:
```
python genomeGTFtools/microsynteny.py -b blast -q query.1-Contigs.cds.gff -d db.1-Contigs.cds.gff
```

and here is the error:
```
# Running command:
genomeGTFtools/microsynteny.py -b blast -q query.1-Contigs.cds.gff -d db.1-Contigs.cds.gff
# Parsing query.1-Contigs.cds.gff  Tue Aug 18 10:57:34 2020
Traceback (most recent call last):
  File "genomeGTFtools/microsynteny.py", line 431, in <module>
    main(sys.argv[1:],sys.stdout)
  File "genomeGTFtools/microsynteny.py", line 417, in main
    querydict = parse_gtf(args.query_gtf, args.no_genes, args.cds_only, exclusionDict, args.query_delimiter)
  File "genomeGTFtools/microsynteny.py", line 129, in parse_gtf
    sys.stderr.write("# Estimated {} genes from {} exons  ".format(len(exonboundaries), sum(len(x) for x in exonboundaries.values() ) ) + time.asctime() + os.linesep)
UnboundLocalError: local variable 'exonboundaries' referenced before assignment

```

[db.1-Contigs.cds.gff.gz](https://github.com/wrf/genomeGTFtools/files/5089355/db.1-Contigs.cds.gff.gz)
[query.1-Contigs.cds.gff.gz](https://github.com/wrf/genomeGTFtools/files/5089356/query.1-Contigs.cds.gff.gz)
[blast.gz](https://github.com/wrf/genomeGTFtools/files/5089354/blast.gz)

**Comment by wrf** [comment]
Hello,
Yes indeed, it is a parsing problem. Many DBs do not include `gene` features for bacterial genome annotation, usually just CDS, since that is all that matters for bacteria, especially if you don't know a priori what is an operon or not. 

It looks like the problem can be fixed from the data you provided by adding
`-c -g`, which means treat CDS as exons/transcripts, and gene features are not explicitly given.

I'll fix this to give a proper warning and then exit, rather than giving the error.
Best

**Comment by sarah872** [comment]
Thanks! It works now.
