### ISSUE TITLE
Add the mRNA, cds features into the Stringtie outfiles?

### ISSUE THREAD

**Issue by Huangyizhong** [wrf/genomeGTFtools#16]
Hi, there. 
   Since I have used the stringtie merge parameters to combined all the gtf file together. As we can see that there are just the transcripts and exons features in the final files.
![image](https://user-images.githubusercontent.com/31943359/124213485-3be2f500-db23-11eb-942d-a4b9369403e2.png)
Is there scripts that can add the gene, mRNA and CDS features into this files, which make it looks like the following files?
![image](https://user-images.githubusercontent.com/31943359/124213922-fd9a0580-db23-11eb-9726-8d39bd1cdbae.png)
Thanks advance!
Sincerely 
Yizhong Huang

**Comment by wrf** [comment]
Hello,
A "normal" GFF would have gene-mRNA-exon-CDS, with column 9 as ID=something;Parent=somethingelse;
You would only get CDS if you know the protein.
There is a script in [misc](https://github.com/wrf/genomeGTFtools/tree/master/misc) that can convert the "gene_ID/transcript_ID" format of stringTie into "ID=;Parent=", called `stringtie_gtf_to_gff3.py`. Otherwise you should predict the proteins and frames using a program like [TransDecoder](https://github.com/TransDecoder/TransDecoder), and follow all of their steps.
Best
WRF

**Comment by Huangyizhong** [comment]
Hi, thanks so much for your kind help. Yes, you are right. I used the stringtie to merge the EVM model results and liftoff results (all for genome annotation), and the EVM model results included the transdecoder parts. All I want to do is just add the gene, mRNA and CDS feature into the files, which  which make it looks like the second files.
