### ISSUE TITLE
merging -K and no -K parameter

### ISSUE THREAD

**Issue by mictadlo** [wrf/genomeGTFtools#8]
Hi,
I ran `blast2genomegff.py` twice. The first one with `-K` (track 2) and second without `-K` (track 3)

```
python blast2genomegff.py -p blastp -b labVSviridiplantae_hybrid_blastp.out -g augustus.hints_utrAGAT.newID.no_remark.gff3 -d uniprot-viridiplantae-reviewed-yes-isoforms.fasta --gff-delimiter "." -G -K -S -x > labVSviridiplantae_hybrid_blastp-K.gff
```
```
python blast2genomegff.py -p blastp -b labVSviridiplantae_hybrid_blastp.out -g augustus.hints_utrAGAT.newID.no_remark.gff3 -d uniprot-viridiplantae-reviewed-yes-isoforms.fasta --gff-delimiter "." -G -S -x > labVSviridiplantae_hybrid_blastp-K.gff
```

![Screen Shot 2020-02-18 at 3 57 09 PM](https://user-images.githubusercontent.com/588297/74708403-0c9e5180-5268-11ea-86f3-2215ac8f667b.png)

However, comparing `NBlab03G03860.1` from the first track it appears that the proteins from track 2 and 3 should not have been split.  

Is there a way to merge those two proteins to make one big one?

Thank you in advance,

Michal

**Comment by wrf** [comment]
The features that you see are based on the protein match and the CDS features. The matched portion does not always start at the first amino acid.
If this is the same GFF annotation file from the other issue, then the version without -K is wrong, since it is starting to count the CDS at the first exon, not the first CDS.

**Comment by mictadlo** [comment]
Hi, I redone completely the GFF3 compare to the previous post. Please find all input files attached for `blast2genomegff.py`. Could you please check why `-K` and without `-K` I have got different results?

Thank you in advance,

Michal

[labVSviridiplantae_hybrid_blastp.out.txt](https://github.com/wrf/genomeGTFtools/files/4222682/labVSviridiplantae_hybrid_blastp.out.txt)
[blast2genome.aa.fasta.txt](https://github.com/wrf/genomeGTFtools/files/4222683/blast2genome.aa.fasta.txt)
[blast2genome.gff.txt](https://github.com/wrf/genomeGTFtools/files/4222684/blast2genome.gff.txt)

**Comment by wrf** [comment]
The `-K` option is to ignore exon features if they are in the same annotation file. If you were using blastx on the full transcripts instead of blastp, then you would want all of the exons.
The proteins are the same, they just start from the first CDS (the correct choice for blastp, with `-K`) or from the first exon (for blastx). They are not split since there is only one HSP for each protein.
